#!/usr/bin/python
import time,sys

sys.stderr.write("1\rDies ist noch eine Test-Fehlermeldung\n2\r")
sys.stderr.flush()
f = sys.stdin.readline()
while f:
	f=f.strip()
	sys.stdout.write("*** RECV "+f+" ***\n")
	sys.stdout.flush()
	f = sys.stdin.readline()
