update=23/2/2008-15:06:12
last_client=cvpcb
[cvpcb]
version=1
NetITyp=0
NetIExt=.net
PkgIExt=.pkg
NetType=0
[cvpcb/libraries]
EquName1=devcms
[common]
NetDir=
[pcbnew]
[pcbnew/libraries]
LibDir=
LibName1=./1wire
LibName2=./local
LibName3=supports
LibName4=connect
LibName5=discret
LibName6=pin_array
LibName7=divers
LibName8=libcms
LibName9=display
LibName10=valves
