#!/bin/bash

# Trigger the NC background processes
# i.e. if the listener hasn't got anything, send to it, making it exits

echo X | nc localhost 50333 >/dev/null 2>&1 || true

trap "rm -f /tmp/nettest_$USER" 0 

sleep 1
set -e
(echo bar;echo quux) | diff -u - /tmp/nettest_$USER
