#!/bin/sh
##
##  Copyright © 2007-2008, Matthias Urlichs <matthias@urlichs.de>
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License (included; see the file LICENSE)
##  for more details.
##

PATH=/usr/local/sbin:/usr/sbin/:$PATH

if ! type -p owserver >/dev/null 2>&1 ; then echo "owserver: not found!"; exit 1 ; fi

owserver --foreground -p 54300 --tester=10  --error_level 5 --error_print 2 \
	> /tmp/owlog_$USER 2>&1 &
echo $! > /tmp/owtest_$USER
sleep 1
