#!/bin/sh
##
##  Copyright © 2007-2008, Matthias Urlichs <matthias@urlichs.de>
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License (included; see the file LICENSE)
##  for more details.
##

test -f test/onewire2_in && cd test
if test ! -f onewire2_in; then
	echo "$0: test/onewire2_in: not found" >&2
	exit 1
fi

if ! test -f ../onewire_params ; then

	cat >&2 <<END
Parameter file not found any more. Do you have some problems ?!?
END
	exit 1
fi

(
	read dev
	read attr
	read attr2
	read val
	read host
	read port

	if test -z "$dev" ; then
		echo "You didn't set a device!"
		exit 2
	fi
	test -n "$attr" || attr=temperature
	test -n "$host" || host=localhost
	test -n "$port" || port=4304

	sed -r \
	    -e "s/$host/_HOST_/g" -e "s/$port/_PORT_/g" \
	    -e "s/$dev/_DEV_/g"   -e "s/$attr/_ATTR_/g" \
	    -e "s/$attr2/_ATTR2_/g"   -e "s/$val/_VAL_/g" \
		-e "s/ATTRgetmsg.* _DEV_ _ATTR_.*: '.*'/ATTRgetmsg DATA/" \
		-e "s/EVENT: thermo.*/EVENT: thermo¦DATA/" \
		-e "s/END: thermo.*/END: thermo¦DATA/" \
		-e "s/instance at 0x[0-9a-fA-F]*/instance at FOO/g" \
		-e "/EVENT: onewire.*scanning/,/EVENT: onewire.*scanned/d" \
		-e "/EVENT: onewire.*scanned/d" \
		-e "s/^[0-9][0-9]*/99/" \
		-e "/DirStart/,/DirStop/d" \
		-e "s/: wait¦(start|stop|done|cancel)¦[0-9.]*¦/: wait¦\1¦×××¦/g" \
		-i real/onewire
) < ../onewire_params
exit $?
