#!/bin/sh
##
##  Copyright © 2007, Matthias Urlichs <matthias@urlichs.de>
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License (included; see the file LICENSE)
##  for more details.
##

test -f test/onewire2_in && cd test
if test ! -f onewire2_in; then
	echo "$0: test/onewire2_in: not found" >&2
	exit 1
fi

if ! test -f ../onewire_params ; then
	cat >&2 <<END
You need to create a file named "onewire_params" which contains four
lines:
* the ID of some device on the 1wire bus
  (find one with "owdir"; a thermometer is good, it's named "10.SOMETHING")
  (do not give the path to the device, the test will find it on its own!)
* some parameter to read ("temperature")
* some parameter to write ("temphigh")
* the value to write (50)
* hostname where a owserver daemon is running; default localhost
* port on which the owserver listens (default, 4304)

Ignore all of this if you do not have a 1wire bus.
END
	exit 1
fi

(
	read dev
	read attr
	read attr2
	read val
	read host
	read port

	if test -z "$dev" ; then
		echo "You didn't set a device!"
		exit 2
	fi
	test -n "$attr" || attr=temperature
	test -n "$host" || host=localhost
	test -n "$port" || port=4304

	echo Testing 1wire on $host:$port for $dev/$attr
	sed -e "s/_HOST_/$host/g" -e "s/_PORT_/$port/g" \
	    -e "s/_ATTR2_/$attr2/g" -e "s/_VAL_/$val/g" \
	    -e "s/_DEV_/$dev/g"   -e "s/_ATTR_/$attr/g" < onewire2_in >onewire2
) < ../onewire_params
exit $?
