#!/bin/sh
##
##  Copyright © 2007-2012, Matthias Urlichs <matthias@urlichs.de>
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License (included; see the file LICENSE)
##  for more details.
##

# Trigger the NC background processes
# i.e. if the listener hasn't got anything, send to it, making it exits

(
sleep 3
sed -re 's/('"'"'remote port'"'"'[^0-9]*)[0-9]*/\1×××/' \
    -i real/rpc
)&

