#!/bin/sh
##
##  Copyright © 2007-2008, Matthias Urlichs <matthias@urlichs.de>
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License (included; see the file LICENSE)
##  for more details.
##

set -e

trap "rm -f /tmp/nc_$USER /tmp/nc_$USER.pid /tmp/f.$$" 0 1

kill -9 $(cat /tmp/nc_$USER.pid) || true
cat >/tmp/f.$$ <<'END'
<172>HomEvenT: Five Warn
END
sed -e "s/ at 0x[0-9A-Fa-f]*/ at 0x×××/g" \
	-i real/syslog

diff -u /tmp/f.$$ /tmp/nc_$USER

