#!/bin/bash
##
##  Copyright © 2007-2008, Matthias Urlichs <matthias@urlichs.de>
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License (included; see the file LICENSE)
##  for more details.
##

PATH=/usr/local/sbin:/usr/sbin/:$PATH

if test -d wago ; then WAGO=wago; else WAGO=../wago; fi

$WAGO/wago --foreground -p 59069 -c $WAGO/wago.sample.csv > /tmp/wagolog_$USER 2>&1 &
echo $! > /tmp/wagotest_$USER

while : ; do 
	nc </dev/null -l localhost 59068 || exit 1
done &
echo $! >> /tmp/wagotest_$USER

sleep 1
