# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainman', '0001_initial_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='password',
            field=models.CharField(default='test', help_text='RabbitMQ password', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='username',
            field=models.CharField(default='test', help_text='RabbitMQ username', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='virtualhost',
            field=models.CharField(default='/test', help_text='RabbitMQ vhost', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='host',
            field=models.CharField(default='localhost', help_text='where to find the RabbitMQ server', max_length=200),
        ),
        migrations.AlterField(
            model_name='site',
            name='port',
            field=models.PositiveIntegerField(default=0, help_text='Port for RabbitMQ'),
        ),
    ]
